### ISSUE TITLE
eng_psf: PS2 DMA4 / DMA7 are implemented incorrectly

### ISSUE THREAD

**Issue by kode54** [nmlgc/aosdk#1]
I thought I'd point out how to fix that. Basically, both are coded to copy twice as many halfwords as they're supposed to. And the DMA7 has its BCR and CHCP registers swapped for some mysterious reason.

The double memory has the following bug effects apparent in released sets:

nenolod's Final Fantasy X rip: DMA4 copies twice as much, compensating for DMA7 being totally broken. Normally, this rip uses simultaneous DMA4 and DMA7 copies to split up transfers of individual samples.

CaitSith2's Final Fantasy 4 rip: DMA4 is used to stream all of the sample data for both playing channels, which breaks completely because it is copying twice as much data as it is supposed to.

**Comment by nmlgc** [comment]
In the long run, it'll probably (I really didn't know anything about this chip and its emulation before) be better anyway to just throw out that old code and merge in [your Highly Experimental repository](https://github.com/kode54/Highly_Experimental). The Final Fantasy X minipsf2 conversion, for example, is still broken even with those fixes.

Still, thanks a lot, that was all I needed to fix the issue myself.

**Comment by kode54** [comment]
Actually, check out my AOPSF repository, at:

https://gitlab.kode54.net/kode54/aopsf

Mainly because it doesn't require a PS2 BIOS derivative to work.

Also, nenolod re-ripped Final Fantasy X so it works on actual hardware, and also Audio Overload, I found the rip by searching for ffx.tbz2, then retagged it a bit:

https://static.kode54.net/ffx.7z

I still need to retouch the SPU playback, I don't think it was actually proper before, looked like it read parts of the header into the SPU RAM.

**Comment by rb6502** [comment]
I know I'm necrothreading pretty hardcore here, but can someone point me to nenolod's Final Fantasy X rip?  We're looking to resurrect Audio Overload and AOSDK and I've been fishing around for fixes people have done to the AOSDK components.  (Richard has the easy part, I'm doing from scratch re-ports to Linux and Windows because GTK 2 was a long time ago).  As part of that it'd be nice to test the rip that these changes fix.

**Comment by nmlgc** [comment]
Still had it lying around:
[ffx_1.zip](https://github.com/nmlgc/aosdk/files/11267622/ffx_1.zip)
[ffx_2.zip](https://github.com/nmlgc/aosdk/files/11267629/ffx_2.zip)

**Comment by rb6502** [comment]
Thanks, I appreciate it!
