### ISSUE TITLE
macOS build

### ISSUE THREAD

**Issue by ron-wolf** [nmlgc/aosdk#3]
Hello, I am trying to compile a 64-bit binary in order to continue using Audio Overload on macOS 10.15, as the [OS X build](https://www.bannister.org/software/ao.htm) found on the website is unfortunately a 32-bit one. I have tried changing the `OSTYPE` environment variable to no avail. My build breaks either way, while performing the following actions (click to reveal console output):

<details><summary>Compiling <code>win32_utf8/src/win32_utf8.h</code> on a Windows build, <a href="https://github.com/thpatch/win32_utf8/blob/84160f6b3bee4dc2f3f24a4456ff1a3f6114ff38/src/win32_utf8.h#L11">due to including <code>Windows.h</code></a>.</summary><p><pre>
$ make
Compiling main.c...
<a href="https://github.com/nmlgc/aosdk/blob/042e91976f3ec5485832ce842e1d14b47c49ac50/main.c#L381-L384">main.c:384:1:</a> warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
Compiling ao.c...
Compiling corlett.c...
Compiling m1sdr.c...
Compiling utils.c...
Compiling mididump.c...
<a href="https://github.com/nmlgc/aosdk/blob/042e91976f3ec5485832ce842e1d14b47c49ac50/main.c#L381-L384">mididump.c:427:16:</a> warning: using the result of an assignment as a condition without
      parentheses [-Wparentheses]
        } while(vchan = vchans_iterate(&iter));
                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
mididump.c:427:16: note: place parentheses around the assignment to silence this warning
        } while(vchan = vchans_iterate(&iter));
                      ^
                (                            )
mididump.c:427:16: note: use '==' to turn this assignment into an equality comparison
        } while(vchan = vchans_iterate(&iter));
                      ^
                      ==
1 warning generated.
Compiling sampledump.c...
Compiling wavedump.c...
Compiling argparse/argparse.c...
Compiling dsnd.c...
In file included from dsnd.c:31:
<a href="https://github.com/thpatch/win32_utf8/blob/84160f6b3bee4dc2f3f24a4456ff1a3f6114ff38/src/win32_utf8.h#L11">./win32_utf8/src/win32_utf8.h:11:10:</a> fatal error: 'Windows.h' file not found
#include &lt;Windows.h&gt;
         ^~~~~~~~~~~
1 error generated.
make: *** [obj/x86_64-apple-darwin18.7.0/dsnd.o] Error 1
</pre></p></details>

<details><summary>Compiling <code>oss.c</code> on a <span title="OSTYPE=linux">Linux build</span>, <a href="https://github.com/nmlgc/aosdk/blob/042e91976f3ec5485832ce842e1d14b47c49ac50/oss.c#L35">due to including <code>sys/soundcard.h</code></a>.</summary><p><pre>
$ OSTYPE=linux make
Compiling main.c...
<a href="https://github.com/nmlgc/aosdk/blob/042e91976f3ec5485832ce842e1d14b47c49ac50/main.c#L381-L384">main.c:384:1:</a> warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
Compiling ao.c...
Compiling corlett.c...
Compiling m1sdr.c...
Compiling utils.c...
Compiling mididump.c...
<a href="https://github.com/nmlgc/aosdk/blob/042e91976f3ec5485832ce842e1d14b47c49ac50/main.c#L381-L384">mididump.c:427:16:</a> warning: using the result of an assignment as a condition without
      parentheses [-Wparentheses]
        } while(vchan = vchans_iterate(&iter));
                ~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
mididump.c:427:16: note: place parentheses around the assignment to silence this warning
        } while(vchan = vchans_iterate(&iter));
                      ^
                (                            )
mididump.c:427:16: note: use '==' to turn this assignment into an equality comparison
        } while(vchan = vchans_iterate(&iter));
                      ^
                      ==
1 warning generated.
Compiling sampledump.c...
Compiling wavedump.c...
Compiling argparse/argparse.c...
Compiling oss.c...
<a href="https://github.com/nmlgc/aosdk/blob/042e91976f3ec5485832ce842e1d14b47c49ac50/oss.c#L35">oss.c:35:10:</a> fatal error: 'sys/soundcard.h' file not found
#include &lt;sys/soundcard.h&gt;
         ^~~~~~~~~~~~~~~~~
1 error generated.
make: *** [obj/x86_64-apple-darwin18.7.0/oss.o] Error 1
</pre></p></details>

Of course, using `NOGUI=1` doesn’t make a difference, as the failures are caused not by GUI libraries but by OS libraries. As such, would it be possible to obtain the code used to compile for Mac, if it is indeed still available? @nmlgc

**Comment by nmlgc** [comment]
If it didn't build in the original version 1.4.8 (737068168178d25e090b4fbdcc6849f652d0b258), no macOS platform code was ever part of the original release, and I'd have to search for it (or reimplement it) myself as well. Given that I've pretty much abandoned this project and don't want to get back into it either, the best I can do right now, without owning any Apple hardware myself, is to fall back on not playing any sound if `/dev/dsp` doesn't exist. That also fixes modern Linux systems which *do* have `sys/soundcard.h` but no `/dev/dsp`, and allows you to still use this code for .wav dumping.
Check the latest commits on `master` for the updates.

**Comment by ron-wolf** [comment]
Greatly appreciate your paying attention to a project you’re no longer maintaining! Looks like I was building on the (then) latest commit, 042e919. I’ll test out the commit and see if it builds. Again, greatly appreciate the project, it really is one-of-a-kind. Also—just out of curiosity—do you know who contributed the macOS code to the project, if you didn’t own any Apple hardware?

**Comment by Sappharad** [comment]
> Hello, I am trying to compile a 64-bit binary in order to continue using Audio Overload on macOS 10.15, as the [OS X build](https://www.bannister.org/software/ao.htm) found on the website is unfortunately a 32-bit one.

You may have already noticed this, but Richard released a 64-bit macOS build of Audio Overload back in November 2019, shortly after your last comment on this post. This issue is probably not relevant anymore.

I had no problem compiling this fork for macOS back in May of 2019 in NOGUI mode. I think I just commented out the stuff you mention above.

**Comment by Sappharad** [comment]
You can probably close this too, since my PR for the ADPCM fix also fixed the macOS build. I'm using
> OSTYPE=linux NOGUI=1 make

to compile.
